# Generated by Django 4.1.5 on 2023-02-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                ("date", models.IntegerField()),
                ("month", models.CharField(max_length=50)),
                ("day", models.CharField(max_length=15)),
                ("time", models.TimeField()),
            ],
        ),
    ]
