# Generated by Django 4.1.5 on 2023-04-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_events_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="title",
            field=models.TextField(max_length=100),
        ),
    ]
