# Generated by Django 4.1.5 on 2023-05-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_events_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
