# Generated by Django 4.1.5 on 2023-05-25 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0002_books_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="publication",
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
    ]
