# Generated by Django 4.1.5 on 2023-05-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0003_books_publication"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyAwards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("name", models.CharField(max_length=5000)),
                ("award", models.CharField(max_length=5000)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentAwards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("name", models.CharField(max_length=5000)),
                ("award", models.CharField(max_length=5000)),
                ("roll_no", models.IntegerField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
    ]
