# Generated by Django 4.1.5 on 2023-05-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0004_facultyawards_studentawards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="author",
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="books",
            name="publication",
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="facultyawards",
            name="award",
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="studentawards",
            name="award",
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="studentawards",
            name="roll_no",
            field=models.IntegerField(null=True),
        ),
    ]
