# Generated by Django 4.1 on 2023-09-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0006_patent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patent",
            name="year",
            field=models.CharField(max_length=50),
        ),
    ]
