# Generated by Django 4.1.5 on 2023-04-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elective",
            name="program",
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.IntegerField(blank=True),
        ),
    ]
