# Generated by Django 4.1 on 2023-08-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_course_credit_course_ltp_elective_credit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program", models.CharField(max_length=50)),
                ("elective", models.BooleanField(default=False)),
                ("semester", models.IntegerField(blank=True)),
                ("code", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=50)),
                ("credit", models.FloatField(blank=True)),
                ("ltp", models.CharField(max_length=10)),
            ],
        ),
    ]
