# Generated by Django 4.1 on 2023-08-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_coursenew"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="coursenew",
            name="code",
            field=models.CharField(max_length=10),
        ),
    ]
