# Generated by Django 4.1 on 2023-08-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0007_alter_course_code_alter_coursenew_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursenew",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
