# Generated by Django 4.1 on 2023-08-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0009_alter_course_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elective",
            name="code",
            field=models.CharField(max_length=20),
        ),
    ]
