# Generated by Django 4.1 on 2023-08-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0010_alter_elective_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elective",
            name="code",
            field=models.CharField(max_length=30),
        ),
    ]
