# Generated by Django 4.1.5 on 2023-04-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcements",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
