# Generated by Django 4.1.5 on 2023-02-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labs",
            name="person",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="papers",
            name="person",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="projects",
            name="worker",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="research",
            name="person",
            field=models.CharField(max_length=500),
        ),
    ]
