# Generated by Django 4.1.5 on 2023-03-06 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_alter_labs_person_alter_papers_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="research",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
