# Generated by Django 4.1.5 on 2023-05-11 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0006_pglabs_delete_labs"),
    ]

    operations = [
        migrations.CreateModel(
            name="UGLabs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("experiments", models.JSONField(null=True)),
                ("equipments", models.JSONField(null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pglabs",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="pglabs",
            name="keywords",
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pglabs",
            name="review",
            field=models.JSONField(null=True),
        ),
    ]
