# Generated by Django 4.1.5 on 2023-02-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "people_cat",
                    models.CharField(
                        choices=[
                            ("Staff", "staff"),
                            ("Faculty", "faculty"),
                            ("Phd", "Phd"),
                            ("MTech", "MTech"),
                            ("BTech", "BTech"),
                            ("Alumni", "Alumni"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=50)),
                ("email", models.URLField()),
                ("details", models.CharField(max_length=10000)),
                ("link", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=500)),
                ("subject", models.CharField(max_length=50)),
            ],
        ),
    ]
