# Generated by Django 4.1.5 on 2023-04-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_alumni_btech_faculty_mtech_phd_staff_delete_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="D:/projects/EE Website/media"
            ),
        ),
        migrations.AlterField(
            model_name="btech",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="D:/projects/EE Website/media"
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="D:/projects/EE Website/media"
            ),
        ),
        migrations.AlterField(
            model_name="mtech",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="D:/projects/EE Website/media"
            ),
        ),
        migrations.AlterField(
            model_name="phd",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="D:/projects/EE Website/media"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="D:/projects/EE Website/media"
            ),
        ),
    ]
