# Generated by Django 4.1 on 2023-08-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0008_faculty_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="subtitle",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
