# Generated by Django 4.1 on 2023-08-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0013_faculty_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="phone",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
