# Generated by Django 4.1 on 2023-10-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0015_ms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
